"""
Django settings for jamshidcms project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG")))

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    # 'grappelli',
    # 'filebrowser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'blog.apps.BlogConfig',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jamshidcms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jamshidcms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get("DB_NAME"),
        'USER': os.environ.get("DB_USER"),
        'PASSWORD': os.environ.get("DB_PASSWORD"),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

# Media files (User Uploaded Images)

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEDITOR CONFIG

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_BROWSE_PATH = "_version/"

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

CKEDITOR_FILENAME_GENERATOR = 'blog.utils.get_filename'

CKEDITOR_RESTRICT_BY_USER = True

CKEDITOR_RESTRICT_BY_DATE = True

CKEDITOR_BROWSE_SHOW_DIRS = True

CKEDITOR_IMAGE_BACKEND = 'pillow'  # Use Pillow for image processing

CKEDITOR_THUMBNAIL_SIZE = (150, 150)

CKEDITOR_ALLOW_NONIMAGE_FILES = False

DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440

# CKEDITOR_JQUERY_URL = 'https://code.jquery.com/jquery-3.6.0.min.js'  # Use a CDN or your own jQuery version


CKEDITOR_CONFIGS = {
    'custom_ckeditor': {
        'toolbar': 'full',
        'height': 400,
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'filebrowserImagePreviewText': ' ',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 1024,
        'image_previewText': ' ',
        'toolbarCanCollapse': True,
        'tabSpaces': 4,

    }
}

# DRF CONFIG

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        # 'rest_framework.renderers.BrowsableAPIRenderer',  # Comment out or remove this line
        'rest_framework.renderers.JSONRenderer',

    ],
    # Other DRF settings...
}

# CORS CONFIG

CORS_ALLOW_HEADERS = ['*']

CORS_ALLOW_METHODS = ['*']

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = False

CORS_ORIGIN_WHITELIST = (
    'http://localhost',
    'http://localhost:5173',
    'http://localhost:8080',
    'https://jamshid.app',
)

CSRF_TRUSTED_ORIGINS = [
    'https://cms.api.jamshid.app'
]

# Filebrowser CONFIG

# FILEBROWSER_DIRECTORY = 'uploads/'
#
# FILEBROWSER_EXTENSIONS = {
#     'Image': ['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff'],
#     'Document': ['.pdf', '.doc', '.rtf', '.txt', '.xls', '.csv'],
#     'Video': ['.mov', '.wmv', '.mpeg', '.mpg', '.avi', '.rm'],
#     'Audio': ['.mp3', '.mp4', '.wav', '.aiff', '.midi', '.m4p']
# }
# FILEBROWSER_SELECT_FORMATS = {
#     'file': ['Image', 'Document', 'Video', 'Audio'],
#     'image': ['Image'],
#     'document': ['Document'],
#     'media': ['Video', 'Audio'],
# }
