# Generated by Django 5.0.1 on 2024-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_content_type_category_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='object_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(max_length=200),
        ),
    ]
