# Generated by Django 5.0.1 on 2024-01-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='object_id',
        ),
    ]
